from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from textwrap import dedent

from schemas import GameSpec, HarnessState, LevelSpec, TestResult


def generate_project(base_dir: Path, state: HarnessState, tests: list[TestResult]) -> Path:
    assert state.game_spec and state.level_spec
    project_dir = unique_project_dir(base_dir, slugify(state.game_spec.title))
    project_dir.mkdir(parents=True, exist_ok=True)
    config = {
        "game_spec": state.game_spec.to_dict(),
        "level_spec": state.level_spec.to_dict(),
        "tests": [row.to_dict() for row in tests],
    }
    (project_dir / "config.json").write_text(json.dumps(config, indent=2))
    (project_dir / "main.py").write_text(runtime_template())
    shutil.copyfile(Path(__file__).resolve().parent / "top_down_engine.py", project_dir / "top_down_engine.py")
    (project_dir / "README.md").write_text(project_readme(state.game_spec, state.level_spec))
    return project_dir


def write_state(project_dir: Path, state: HarnessState):
    (project_dir / "state.json").write_text(json.dumps(state.to_dict(), indent=2))
    (project_dir / "test_report.json").write_text(json.dumps([row.to_dict() for row in state.test_results], indent=2))


def unique_project_dir(base_dir: Path, slug: str) -> Path:
    path = base_dir / slug
    if not path.exists():
        return path
    idx = 2
    while (base_dir / f"{slug}_{idx}").exists():
        idx += 1
    return base_dir / f"{slug}_{idx}"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.lower()).strip("_")
    return slug or "generated_game"


def project_readme(spec: GameSpec, level: LevelSpec) -> str:
    return dedent(
        f"""
        # {spec.title}

        Generated by the schema-driven agent harness.

        Original design:
        - Genre: `{spec.genre}`
        - Theme: `{spec.theme}`
        - Difficulty: `{spec.difficulty}`
        - Objective: {spec.objective}
        - Mechanics: {", ".join(spec.mechanics)}

        Run:

        ```bash
        python main.py
        ```

        Controls:
        - Top-down: WASD/arrows move, E/Space interact.
        - Platformer: A/D or arrows move, Space/W/up jump.
        - R reset, Esc quit.

        Level:
        - Size: {level.width} x {level.height}
        - Entities: {len(level.entities)}
        """
    ).strip() + "\n"


def runtime_template() -> str:
    return dedent(
        r'''
        from __future__ import annotations

        import json
        from pathlib import Path

        import pygame

        from top_down_engine import TopDownState


        COLORS = {
            "bg": (22, 24, 30),
            "wall": (72, 76, 86),
            "player": (70, 130, 220),
            "goal": (80, 190, 110),
            "collectible": (235, 205, 80),
            "enemy": (210, 80, 80),
            "key": (245, 210, 90),
            "door": (140, 95, 55),
            "source": (180, 145, 95),
            "container": (95, 155, 180),
            "text": (238, 238, 230),
        }


        def load_config():
            return json.loads((Path(__file__).resolve().parent / "config.json").read_text())


        class Game:
            def __init__(self, config):
                self.config = config
                self.spec = config["game_spec"]
                self.level = config["level_spec"]
                self.tile = self.level["tile_size"]
                self.reset()

            def reset(self):
                self.player = [self.level["spawn"][0] * self.tile, self.level["spawn"][1] * self.tile]
                self.vel = [0, 0]
                self.inventory = set()
                self.collected = set()
                self.open_doors = set()
                self.done = False
                self.failed = False
                self.steps = 0
                self.message = "ready"
                self.carrying = None
                self.move_cooldown = 0
                self.entities = [dict(e) for e in self.level["entities"]]
                self.core = TopDownState.from_config(self.config) if self.level["genre"] == "top_down_adventure" else None
                self.harvested_sources = self.core.harvested_sources if self.core else set()
                self.delivered_sources = self.core.delivered_sources if self.core else set()
                self.workflow_steps = self.core.workflow_steps if self.core else {}

            def update(self, keys):
                if self.done or self.failed:
                    return
                self.steps += 1
                if self.level["genre"] == "2d_platformer":
                    self.update_platformer(keys)
                else:
                    self.update_top_down(keys)
                self.update_enemies()
                self.check_entity_collisions()
                if self.steps > 2500:
                    self.failed = True

            def update_top_down(self, keys):
                if self.move_cooldown > 0:
                    self.move_cooldown -= 1
                    return
                dx = (keys[pygame.K_RIGHT] or keys[pygame.K_d]) - (keys[pygame.K_LEFT] or keys[pygame.K_a])
                dy = (keys[pygame.K_DOWN] or keys[pygame.K_s]) - (keys[pygame.K_UP] or keys[pygame.K_w])
                if dx and dy:
                    dy = 0
                if not dx and not dy:
                    return
                action = "right" if dx > 0 else "left" if dx < 0 else "down" if dy > 0 else "up"
                self.core.apply(action)
                self.sync_from_core()
                self.move_cooldown = 6

            def update_platformer(self, keys):
                dx = (keys[pygame.K_RIGHT] or keys[pygame.K_d]) - (keys[pygame.K_LEFT] or keys[pygame.K_a])
                self.vel[0] = dx * 4
                self.vel[1] = min(14, self.vel[1] + 0.7)
                if (keys[pygame.K_SPACE] or keys[pygame.K_UP] or keys[pygame.K_w]) and self.on_ground():
                    self.vel[1] = -12
                self.try_move(self.vel[0], 0)
                self.try_move(0, self.vel[1])

            def try_move(self, dx, dy):
                nx, ny = self.player[0] + dx, self.player[1] + dy
                if not self.collides(nx, self.player[1]):
                    self.player[0] = nx
                else:
                    self.vel[0] = 0
                if not self.collides(self.player[0], ny):
                    self.player[1] = ny
                else:
                    if dy > 0:
                        self.player[1] = int((self.player[1] + self.tile - 1) // self.tile) * self.tile
                    self.vel[1] = 0

            def collides(self, px, py):
                rect = pygame.Rect(px + 7, py + 7, self.tile - 14, self.tile - 14)
                for y, row in enumerate(self.level["layout"]):
                    for x, tile in enumerate(row):
                        if tile == "#" and rect.colliderect(pygame.Rect(x * self.tile, y * self.tile, self.tile, self.tile)):
                            return True
                for entity in self.entities:
                    if entity["type"] == "door" and entity["id"] not in self.open_doors:
                        ex, ey = entity["pos"]
                        if rect.colliderect(pygame.Rect(ex * self.tile, ey * self.tile, self.tile, self.tile)):
                            return True
                return False

            def tile_at(self, x, y):
                if x < 0 or y < 0 or x >= self.level["width"] or y >= self.level["height"]:
                    return "#"
                return self.level["layout"][y][x]

            def passable_tile(self, pos):
                x, y = pos
                if x < 0 or y < 0 or x >= self.level["width"] or y >= self.level["height"]:
                    return False
                if self.level["layout"][y][x] == "#":
                    return False
                for entity in self.entities:
                    if entity["type"] == "door" and entity["id"] not in self.open_doors and tuple(entity["pos"]) == tuple(pos):
                        return False
                return True

            def on_ground(self):
                return self.collides(self.player[0], self.player[1] + 2)

            def interact(self):
                if self.core is not None:
                    self.core.apply("interact")
                    self.sync_from_core()
                    return
                self.message = "platformer uses movement collision; no interact action"

            def update_enemies(self):
                if self.core is not None:
                    return
                for entity in self.entities:
                    if entity["type"] != "enemy":
                        continue
                    props = entity.setdefault("properties", {})
                    origin = props.setdefault("origin", list(entity["pos"]))
                    direction = props.setdefault("direction", 1)
                    axis = props.get("axis", "horizontal")
                    patrol_range = int(props.get("range", 3))
                    if self.steps % 12 != 0:
                        continue
                    if entity.get("behavior") == "chase_player":
                        candidate = self.next_chase_step(entity)
                        if candidate is not None:
                            entity["pos"] = candidate
                        continue
                    idx = 0 if axis == "horizontal" else 1
                    candidate = list(entity["pos"])
                    candidate[idx] += direction
                    if self.enemy_can_move_to(tuple(candidate)) and abs(candidate[idx] - origin[idx]) <= patrol_range:
                        entity["pos"] = candidate
                    else:
                        props["direction"] = -direction

            def enemy_can_move_to(self, pos):
                x, y = pos
                return self.tile_at(x, y) != "#" and self.tile_at(x, y + 1) == "#"

            def next_chase_step(self, entity):
                ex, ey = entity["pos"]
                px, py = self.player_tile()
                step = 1 if px > ex else -1 if px < ex else 0
                if step == 0:
                    return None
                candidate = (ex + step, ey)
                return list(candidate) if self.enemy_can_move_to(candidate) else None

            def check_entity_collisions(self):
                if self.core is not None:
                    self.sync_from_core()
                    return
                tile = self.player_tile()
                requires_all = self.spec.get("win_condition", {}).get("requires_all_collectibles", False)
                for entity in self.entities:
                    if entity["id"] in self.collected:
                        continue
                    if self.level["genre"] == "2d_platformer" and entity["type"] == "collectible" and tile == tuple(entity["pos"]):
                        self.collected.add(entity["id"])
                    elif entity["type"] == "enemy" and tile == tuple(entity["pos"]):
                        self.failed = True
                    elif entity["type"] == "goal" and tile == tuple(entity["pos"]):
                        if not requires_all or self.all_collectibles_collected():
                            self.done = True

            def all_collectibles_collected(self):
                collectibles = [e["id"] for e in self.entities if e["type"] in {"collectible", "key"}]
                return all(entity_id in self.collected for entity_id in collectibles)

            def player_tile(self):
                return int((self.player[0] + self.tile / 2) // self.tile), int((self.player[1] + self.tile / 2) // self.tile)

            def sync_from_core(self):
                if self.core is None:
                    return
                self.player = [self.core.pos[0] * self.tile, self.core.pos[1] * self.tile]
                self.inventory = self.core.inventory
                self.collected = self.core.collected
                self.open_doors = self.core.open_doors
                self.harvested_sources = self.core.harvested_sources
                self.delivered_sources = self.core.delivered_sources
                self.workflow_steps = self.core.workflow_steps
                self.carrying = self.core.carrying
                self.entities = self.core.entities
                self.done = self.core.done
                self.failed = self.core.failed
                self.steps = self.core.steps
                self.message = self.core.message

            def draw(self, screen, font):
                screen.fill(COLORS["bg"])
                for y, row in enumerate(self.level["layout"]):
                    for x, tile in enumerate(row):
                        if tile == "#":
                            pygame.draw.rect(screen, COLORS["wall"], rect(self.tile, x, y))
                for entity in self.entities:
                    if entity["id"] in self.collected or entity["id"] in self.delivered_sources or entity["id"] in self.harvested_sources:
                        continue
                    if entity["type"] == "door" and entity["id"] in self.open_doors:
                        continue
                    color = COLORS.get(entity["type"], (180, 180, 180))
                    pygame.draw.rect(screen, color, rect(self.tile, *entity["pos"]).inflate(-8, -8), border_radius=4)
                    label = font.render(label_for(entity), True, (20, 20, 24))
                    screen.blit(label, label.get_rect(center=rect(self.tile, *entity["pos"]).center))
                pygame.draw.rect(screen, COLORS["player"], pygame.Rect(self.player[0] + 4, self.player[1] + 4, self.tile - 8, self.tile - 8), border_radius=4)
                status = "SUCCESS" if self.done else "FAILED" if self.failed else self.spec["objective"]
                carried = self.carrying["resource"] if self.carrying else "none"
                text = font.render(f"{self.spec['title']} | {status} | {self.message} | carried={carried} delivered={len(self.delivered_sources)} collected={len(self.collected)}", True, COLORS["text"])
                screen.blit(text, (10, self.level["height"] * self.tile + 10))


        def rect(tile, x, y):
            return pygame.Rect(x * tile, y * tile, tile, tile)


        def dist(a, b):
            return abs(a[0] - b[0]) + abs(a[1] - b[1])


        def label_for(entity):
            if entity["type"] in {"source", "container", "collectible", "enemy"}:
                return initial(entity.get("name", entity["type"]))
            return {"goal": "G", "key": "K", "door": "D"}.get(entity["type"], initial(entity.get("name", "?")))


        def initial(value):
            for char in str(value):
                if char.isalnum():
                    return char.upper()
            return "?"


        def normalize_name(value):
            return "".join(char.lower() for char in str(value or "") if char.isalnum())


        def main():
            pygame.init()
            config = load_config()
            game = Game(config)
            w = game.level["width"] * game.tile
            h = game.level["height"] * game.tile + 46
            screen = pygame.display.set_mode((w, h))
            pygame.display.set_caption(game.spec["title"])
            font = pygame.font.SysFont("arial", 16)
            clock = pygame.time.Clock()
            running = True
            while running:
                for event in pygame.event.get():
                    if event.type == pygame.QUIT:
                        running = False
                    elif event.type == pygame.KEYDOWN:
                        if event.key == pygame.K_ESCAPE:
                            running = False
                        elif event.key == pygame.K_r:
                            game.reset()
                        elif event.key in {pygame.K_e, pygame.K_SPACE}:
                            game.interact()
                game.update(pygame.key.get_pressed())
                game.draw(screen, font)
                pygame.display.flip()
                clock.tick(60)
            pygame.quit()


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()
